---
apiVersion: v1
kind: Service
metadata:
  name: db-svc
  labels:
    app: wordpress
spec:
  ports:
    - port: 3306
      targetPort: 3306
  selector:
    app: wordpress
    tier: mysql
  clusterIP: None
